export { LogoutSvg } from 'src/assets/icons/logout.tsx'
export { Close } from 'src/assets/icons/close.tsx'
export { EyeSlash } from 'src/assets/icons/eye-slash.tsx'
export { Eye } from 'src/assets/icons/eye.tsx'
export { Search } from 'src/assets/icons/search.tsx'
export { ArrowDown } from 'src/assets/icons/arrow-down.tsx'
export { Check } from 'src/assets/icons/check.tsx'
export { Logo } from 'src/assets/icons/logo.tsx'
export { ProfileAvatar } from 'src/assets/icons/userAvatarTest.tsx'
export { ChangePhoto } from 'src/assets/icons/changePhoto.tsx'
export { Redactor } from 'src/assets/icons/redactor.tsx'
export { Chevron } from 'src/assets/icons/chevron-up.tsx'
export { Play } from 'src/assets/icons/play.tsx'
export { Delete } from 'src/assets/icons/delete.tsx'
export { default as StarOutline } from 'src/assets/icons/star-outline.tsx'
export { default as Star } from 'src/assets/icons/star.tsx'
